# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
kotlin = "2.0.0"
compose = "1.7.0-dev1703"
material3-datatable = "0.5.1"
voyager = "1.1.0-beta02"
jSystemThemeDetector = "3.9.1"
pdfbox = "3.0.2"
kotlinx-coroutines = "1.9.0-RC"
ktorm = "4.0.0"
sqlite = "3.46.0.0"
koin = "3.5.6"
slf4j = "2.0.13"
jasypt = "1.9.3"

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
compose-compiler-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
compose-gradle-plugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-screenmodel = { module = "cafe.adriel.voyager:voyager-screenmodel", version.ref = "voyager" }
material3-datatable = { module = "com.seanproctor:data-table-material3", version.ref = "material3-datatable" }
pdfbox = { module = "org.apache.pdfbox:pdfbox", version.ref = "pdfbox" }
jSystemThemeDetector = { module = "com.github.Dansoftowner:jSystemThemeDetector", version.ref = "jSystemThemeDetector" }
ktorm-core = { module = "org.ktorm:ktorm-core", version.ref = "ktorm" }
ktorm-sqlite = { module = "org.ktorm:ktorm-support-sqlite", version.ref = "ktorm" }
jdbc-sqlite = { module = "io.github.willena:sqlite-jdbc", version.ref = "sqlite" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
jasypt = { module = "org.jasypt:jasypt", version.ref = "jasypt" }
